stages:
  - run

run on freebox:
  stage: run
  image: registry.gitlab.com/kibalabs/kiba/docker-images/ssh-able:latest
  variables:
    RUNNABLE_DIRECTORY: "~/deployments/$CI_PROJECT_PATH/$CI_COMMIT_SHORT_SHA"
  before_script:
    - add-ssh-key "${FREEBOX_SSH_KEY}"
  script:
    - ssh-add -l
    - ssh $FREEBOX_USER@$FREEBOX_URL "
        rm -rf $RUNNABLE_DIRECTORY &&
        git clone $CI_REPOSITORY_URL $RUNNABLE_DIRECTORY &&
        cd $RUNNABLE_DIRECTORY &&
        ./run.sh
      "

run on certbox:
  stage: run
  image: registry.gitlab.com/kibalabs/kiba/docker-images/ssh-able:latest
  variables:
    RUNNABLE_DIRECTORY: "~/deployments/$CI_PROJECT_PATH/$CI_COMMIT_SHORT_SHA"
  before_script:
    - add-ssh-key "${CERTBOX_SSH_KEY}"
  script:
    - ssh-add -l
    - ssh $CERTBOX_USER@$CERTBOX_URL "
        rm -rf $RUNNABLE_DIRECTORY &&
        git clone $CI_REPOSITORY_URL $RUNNABLE_DIRECTORY &&
        cd $RUNNABLE_DIRECTORY &&
        ./run-nossl.sh
      "
