before_script:
  - echo $CI_PROJECT_NAME
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$FREEBOX_SSH_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

deploy:
  stage: deploy
  script:
    - ssh $FREEBOX_USER@$FREEBOX_URL "
        cd ~/Projects/Server-Routing && 
        git pull &&
        ./src/run.sh
        "
